# Generated by Django 5.1.4 on 2025-01-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('both', 'Both')], max_length=20)),
                ('event_type', models.CharField(choices=[('dual', 'Dual'), ('individual', 'Individual'), ('both', 'Both')], max_length=50)),
                ('style', models.CharField(choices=[('folkstyle', 'Folkstyle'), ('freestyle', 'Freestyle'), ('both', 'Both')], max_length=50)),
                ('flyer_url', models.URLField(blank=True, null=True)),
                ('club_name', models.CharField(max_length=255)),
                ('tournament_director', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TournamentDirector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=10)),
                ('preferred_age_group', models.CharField(max_length=50)),
                ('preferred_gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('both', 'Both')], max_length=20)),
                ('preferred_style', models.CharField(choices=[('folkstyle', 'Folkstyle'), ('freestyle', 'Freestyle'), ('both', 'Both')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
